config/routes.rb
Rails.application.routes.draw do

 # get 'comments/create'
 # get 'article/show'

  resources :articles do
    resources :comments
  end

  root controller: :landing, action: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  validates :title, presence: true
  validates :content, presence: true
  validates :author, presence: true

  after_create :whatever
  def whatever

  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates_presence_of :content
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)

    if @article.save
      flash[:notice] = 'Article was successfully created.'
      redirect_to @article
    else
      render :new
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  private

  def article_params
    params[:article].permit(:title, :content, :author)

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    article = Article.find(params[:article_id])
    Comment.create(email: params[:email],
                   content: params[:comment],
                   article: article)
    flash[:notice] = 'Your comment was added successfully'
    redirect_to article_path(article)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.content %></p>

<%= form_with url: article_comments_path(@article) do |form| %>
  <%= form.label :email %>
  <%=form.text_field :email %>
  <%=form.label :comment %>
  <%=form.text_field :comment %>
  <%= form.submit 'Create Comment' %>
<% end %>

app/views/landing/index.html.erb
<%= link_to 'new article', '/articles/new' %>

<ul>
  <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article_path(article) %><br />
        <%= article.content %>
        <p>Written by <%= article.author%> at <%= article.created_at.strftime('%Y-%m-%d') %></p>
      </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>

  </body>
</html>